{
  device: "cuda",
  model_name: "Qwen/Qwen1.5-0.5B-Chat",
  model_kwargs: {
    torch_dtype: "auto",
  },
  faiss_kwargs: {
    index_path: scripts/vector_database/data/PQ128.index,
    embedder: null,
    dataset: "scripts/dataset/data/dataset.db",
  },
  pretrained_model_path: "checkpoints/step800",
}